import React from 'react';
import JobCard from './JobCard';
import jobsData from '../../data/jobs.json';

export default function JobList() {
  // In a real automated setup, jobsData is generated by a scraper
  const jobs = jobsData.jobs;

  return (
    <div className="job-list">
      {jobs.map((job) => (
        <JobCard key={job.id} job={job} />
      ))}
    </div>
  );
}
